default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/hadialqattan/pycln
    rev: v1.3.1
    hooks:
    -   id: pycln
        args: [--all]
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        additional_dependencies: [toml]
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
            - pyflakes
            - pycodestyle
            - flake8-bugbear
            - flake8-comprehensions
            - flake8-eradicate
            - flake8-mutable
            - flake8-simplify
            - flake8-builtins
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.6
    hooks:
    -   id: python-bandit-vulnerability-check
        args: [-ll, -ii, --exclude, ./.venv/*, --recursive, .]
        pass_filenames: false
        always_run: true
